repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-executables-have-shebangs

    - repo: https://github.com/PyCQA/flake8
      rev: 7.0.0
      hooks:
        - id: flake8
          #additional_dependencies:
          #    - "flake8-bugbear"

    #- repo: https://github.com/shellcheck-py/shellcheck-py
    #  rev: v0.9.0.5
    #  hooks:
    #      - id: shellcheck

    #- repo: https://github.com/igorshubovych/markdownlint-cli
    #  rev: v0.33.0
    #  hooks:
    #      - id: markdownlint
    #        args: ['--fix']
