name: CI

on: [push, pull_request]

# Lint code using flake8 and run unit tests using pytest
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run Linter
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.7"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        #with:
        #  plugins: "flake8-bugbear"