name: Lint

on: [push, pull_request]

jobs:
  help-check:
    runs-on: ubuntu-latest
    name: Help Check
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      # Cached for subsequent steps, see:
      # https://github.com/actions/setup-python#caching-packages-dependencies
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.7"
          cache: "pip"

      - name: Install all py-scripts dependencies
        run: python py-scripts/update_dependencies.py

      - name: Run help check
        run: |
          cd py-scripts
          bash lf_help_check.bash